name: Build and deploy Node.js app to Azure Web App - anish-todo

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install mongod
        run: |
          sudo apt-get install libcurl4 openssl liblzma5 gzip
          wget https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-amazon2-6.0.2.tgz -O mongo.tgz
          gzip -d mongo.tgz
          tar -xf mongo.tar
          cd mongodb-linux-x86_64-amazon2-6.0.2/bin/
          sudo mv mongod /bin/mongod

      - name: npm install, build, and test for the front
        run: |
          npm install
          CI='' npm run build --if-present

      - name: npm install for api
        run: |
          cd api
          npm install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'anish-todo'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile }}
          package: .
          
      - name: Start MongoDB server
        run: |
          mongod&
          disown
          cd api
          npm run start
